name: strawberry_classfication
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.0
  - pip:
    - langchain==0.2.6
    - langchain-openai==0.1.14
    - numpy==1.26.4
    - matplotlib==3.9.0
    - onnx==1.16.1
    - onnxruntime==1.18.0
    - opencv-python==4.10.0.82
    - tensorflow==2.15.0
    - pandas==2.2.2
    - path==16.14.0
    - seaborn==0.13.2
    - streamlit==1.36.0